name: Python package

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine build virtualenv
        python -m pip install -r requirements.dev.txt
        python -m pip install pdoc
    - name: Build package
      run: |
        python -m build
    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
    - name: Publish docs
      env:
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.CORP_PIPELINES_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CORP_PIPELINES_SECRET_KEY }}
        DISTRIBUTION_ID: ${{ secrets.CORP_ECHOSTREAM_NODE_DOCS_DISTRIBUTION_ID }}
      run: |
        pdoc echostream_node -o docs --footer-text "echostream-node `grep "version" setup.cfg | awk '{print $3}'`"
        aws s3 sync docs/ s3://docs-echostream-node-echo-stream/ --sse
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
  start-runner:
    name: Start self-hosted EC2 runner
    needs:
      - build
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_RUNNER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RUNNER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_RUNNER_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.AWS_RUNNER_GITHUB_TOKEN }}
          ec2-image-id: ${{ secrets.AWS_RUNNER_PYTHON_EC2_IMAGE_ID }}
          ec2-instance-type: ${{ secrets.AWS_RUNNER_EC2_INSTANCE_TYPE }}
          subnet-id: ${{ secrets.AWS_RUNNER_SUBNET_ID }}
          security-group-id: ${{ secrets.AWS_RUNNER_SECURITY_GROUP_ID }}
          iam-role-name: ${{ secrets.AWS_RUNNER_IAM_ROLE_NAME }}
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "github-python-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
  layer:
    name: Build and deploy lambda layer
    needs:
      - start-runner
      - build
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Install package into python dir
        run: |
          pip3.9 install --disable-pip-version-check -t python dist/echostream_node-*-py3-none-any.whl
          cd python
          rm -rf urllib3* six* simplejson* s3transfer* python_dateutil* jmespath* botocore* boto3*
          cd ..
          zip -r echostream-node.zip python/
          pip3.9 install --disable-pip-version-check boto3
          echo "AWS_ACCESS_KEY_ID=${{ secrets.ARTIFACTS_PIPELINES_ACCESS_KEY  }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.ARTIFACTS_PIPELINES_SECRET_KEY }}" >> $GITHUB_ENV
          python3.9 publish_layers.py echostream-node.zip ${GITHUB_REF##*/}
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - build
      - layer
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_RUNNER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RUNNER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_RUNNER_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.AWS_RUNNER_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
